### ISSUE TITLE
Output tensors are always returned on CPU

### ISSUE THREAD

**Issue by amircodota** [triton-inference-server/onnxruntime_backend#134] opened 2022-07-28 06:51 UTC
**Description**

Working with the onnx backend, outputs are always returned on cpu, resulting in bad performance.

**Triton Information**
Tried with versions 22.01 and 22.06, reproduced on both.

Are you using the Triton container or did you build it yourself?

container

Working with a GPT model, and trying to generate many tokens in a single request to a python BLS script, performace is far from what I see when working with the onnx runtime directly.
Invoking the outputs `is_cpu` method returns true, although the model is loaded in an A100 GPU.

Turning on verbose logging, I see a lot of 

```
I0727 19:38:59.729185 1 onnxruntime.cc:1508] Output Properties Unavailable. Using cpu as preferred location for output: {output name}
```

I also see a lot of these messages (though I'm not sure it is related):

```
2022-07-27 19:38:56.921053486 [I:onnxruntime:log, fallback_cpu_capability.cc:143 GetCpuPreferredNodes] ORT optimization- Force fallback to CPU execution for node: Unsqueeze_1913 because the CPU execution path is deemed faster than overhead involved with execution on other EPs  capable of executing this node
```

There seems to be other similar issues.

https://github.com/triton-inference-server/server/issues/4639

https://github.com/triton-inference-server/server/issues/3857 - This one was appearantly fixed in 22.02, but the issue still reproduces for me in 22.06.

**Expected behavior**
Outputs should be returned on GPU

**Comment by Tabrizian** [comment] 2022-07-28 14:59
Duplicate of https://github.com/triton-inference-server/server/issues/4639. Lets continue the discussion there.

**Closed by Tabrizian** 2022-07-28 14:59 UTC
