### ISSUE TITLE
Guidance on building Onnx backend without docker

### ISSUE THREAD

**Issue by smijolovic** [triton-inference-server/onnxruntime_backend#65] opened 2021-09-07 18:56 UTC
The current build without Docker documentation works on the latest release of triton, but the guidance on building the backend of ONNX is very vague:

"Some of the backends may use Docker as part of their build (for example ONNX Runtime and OpenVINO). If you don't want to use Docker in those cases you must consult the build process for those backends."

In looking at the Cmake file and the readme for the ONNX backend, there are still references to containers in the cmake step:
-DTRITON_BUILD_CONTAINER_VERSION

So it's not very clear for building without a container.

With the assumption that all dependencies for Triton are met (as we know they do since we are able to build from source), and the ONNX runtime is built and available, is it possible to get more clarity on the actual process for the backend without building it in a container?

**Comment by askhade** [comment] 2021-09-13 18:17
If you have built ort already then you can provide the binary paths when building the backend - https://github.com/triton-inference-server/onnxruntime_backend/blob/main/CMakeLists.txt#L34

Example: 
cmake -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_ONNXRUNTIME_INCLUDE_PATHS=<ort headers path> -DTRITON_ONNXRUNTIME_LIB_PATHS=<path to ort binaries>-DTRITON_BUILD_CONTAINER_VERSION=<version> ..

make install

**Comment by askhade** [comment] 2021-09-13 18:29
Duplicate of #40 . Closing this issue.

**Closed by askhade** 2021-09-13 18:29 UTC
